#!/usr/bin/env bash
set -x
TTYSAVE="/tmp/retrobox-ttysave"

if [ $# -gt 1 ]; then exit 1; fi

NO_STOP=""
if [[ "$1" == "-n" ]]; then
	NO_STOP="-n"
else
	exit 1
fi

sudo "/usr/local/bin/go2tty" "${NO_STOP}" "$(cat "${TTYSAVE}")"
rm "${TTYSAVE}"
exit $?
