# Ficheros
config=/var/penguin/juegos/retrobox/batocera.conf

# Raíz y logs
root=/var/penguin/juegos/retrobox
log=/var/penguin/juegos/retrobox/logs

# ROMs y saves (root los infiere, pero explícitos por si acaso)
saves=/var/penguin/juegos/retrobox/saves
screenshots=/var/penguin/juegos/retrobox/screenshots

# Temas
system.themes=/var/penguin/juegos/retrobox/resources/themes
themes=/var/penguin/juegos/retrobox/frontend/.emulationstation/themes

# Música
system.music=/var/penguin/juegos/retrobox/resources/music
music=/var/penguin/juegos/retrobox/music

# Decoraciones/bezels
system.decorations=/var/penguin/juegos/retrobox/resources/datainit/decorations
decorations=/var/penguin/juegos/retrobox/decorations

# Shaders
system.shaders=/var/penguin/juegos/retrobox/resources/shaders/configs
shaders=/var/penguin/juegos/retrobox/shaders/configs

# Videofilters
system.videofilters=/var/penguin/juegos/retrobox/resources/videofilters
videofilters=/var/penguin/juegos/retrobox/videofilters

# RetroAchievement sounds
system.retroachievementsounds=/var/penguin/juegos/retrobox/resources/sounds/retroachievements
retroachievementsounds=/var/penguin/juegos/retrobox/sounds/retroachievements

# Padtokey (evmapy)
system.padtokey=/var/penguin/juegos/retrobox/resources/evmapy
padtokey=/var/penguin/juegos/retrobox/configs/evmapy

# Zonas horarias
timezones=/usr/share/zoneinfo
