# Ficheros
config=/var/penguin/juegos/retrobox/batocera.conf

# Raíz y logs
root=/var/penguin/juegos/retrobox
log=/var/penguin/juegos/retrobox/logs

# ROMs y saves (root los infiere, pero explícitos por si acaso)
saves=/var/penguin/juegos/retrobox/saves
screenshots=/var/penguin/juegos/retrobox/screenshots

# Temas
themes=/var/penguin/juegos/retrobox/frontend/themes

# Música
music=/var/penguin/juegos/retrobox/frontend/music

# Decoraciones/bezels
decorations=/var/penguin/juegos/retrobox/decorations

# Shaders
shaders=/var/penguin/juegos/retrobox/shaders/configs

# Videofilters
videofilters=/var/penguin/juegos/retrobox/emulators/retroarch/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/filters/video

# Videofilters
audiofilters=/var/penguin/juegos/retrobox/emulators/retroarch/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/filters/audio

# RetroAchievement sounds
retroachievementsounds=/var/penguin/juegos/retrobox/frontend/retroachievements-sounds

# Padtokey (gamepadly)
system.padtokey=/var/penguin/juegos/retrobox/resources/utils/gamepadly/profiles
padtokey=/var/penguin/juegos/retrobox/resources/utils/gamepadly/user_profiles

# Zonas horarias
timezones=/usr/share/zoneinfo
