#!/bin/bash

# phase 1: before ES starts
CNT=20
while [ $(ps aux | awk '$11 ~ /(^|\/)emulationstation$/' | wc -l) -lt 1 ]; do
	sleep 2
	CNT=$((CNT - 1))
	if [ $CNT -eq 0 ]; then
		exit 1
	fi
done

# phase 2: ES is up and running
while [ $(ps aux | awk '$11 ~ /(^|\/)emulationstation$/' | wc -l) -ge 1 ]; do
	sleep 2
done

exit 0


