#!/bin/bash

if [ $# -gt 1 ]; then exit 1; fi

daemon() {
    sleep 1
    CNT=7

    ${1} &

    while ! pgrep -fi emulationstation >/dev/null 2>&1; do
        sleep 5
        CNT=$((CNT - 1))
        if [ $CNT -le 0 ]; then
            exit 1
        fi
    done

    while pgrep -fi emulationstation >/dev/null 2>&1; do
        sleep 2
    done
    sleep 1
    exit 0

}

if [[ $1 == "-d" ]]; then
    daemon "${0}"
fi

VT_DESTINO=8

vt_origen=$(sed 's/tty//' /sys/class/tty/tty0/active)
echo "$vt_origen" >"/tmp/retrobox-ttysave"

sudo /usr/local/bin/go2tty "$VT_DESTINO"

exit $?
