# Ficheros
config=/home/manuel/.local/share/batocera/batocera.conf

# Raíz y logs
root=/home/manuel/.local/share/batocera
log=/home/manuel/.local/share/batocera/logs

# ROMs y saves (root los infiere, pero explícitos por si acaso)
saves=/home/manuel/.local/share/batocera/saves
screenshots=/home/manuel/.local/share/batocera/screenshots

# Temas
system.themes=/home/manuel/proyectos/batocera-emulationstation/themes
themes=/home/manuel/.local/share/batocera/.emulationstation/themes

# Música
system.music=/home/manuel/.local/share/batocera/resources/music
music=/home/manuel/.local/share/batocera/music

# Decoraciones/bezels
system.decorations=/home/manuel/.local/share/batocera/resources/datainit/decorations
decorations=/home/manuel/.local/share/batocera/decorations

# Shaders
system.shaders=/home/manuel/.local/share/batocera/resources/shaders/configs
shaders=/home/manuel/.local/share/batocera/shaders/configs

# Videofilters
system.videofilters=/home/manuel/.local/share/batocera/resources/videofilters
videofilters=/home/manuel/.local/share/batocera/videofilters

# RetroAchievement sounds
system.retroachievementsounds=/home/manuel/.local/share/batocera/resources/sounds/retroachievements
retroachievementsounds=/home/manuel/.local/share/batocera/sounds/retroachievements

# Padtokey (evmapy)
system.padtokey=/home/manuel/.local/share/batocera/resources/evmapy
padtokey=/home/manuel/.local/share/batocera/configs/evmapy

# Zonas horarias
timezones=/usr/share/zoneinfo
