emuconfig:
  fullname: emuconfig
  manufacturer: _Retrobox
  release: None
  hardware: system
  path: ../resources/es_menu
  extension:
  - .menu
  command: python3 ../runtime/launcher/emulatorlauncher.py %CONTROLLERSCONFIG% -system %SYSTEM% -rom %ROM% -gameinfoxml %GAMEINFOXML% -systemname %SYSTEMNAME%
  platform:
  - emuconfig
  theme: emuconfig
