#!/bin/bash

if test -z "${DISPLAY}"
then
	export DISPLAY=$(getLocalXDisplay)
fi

"${USERDATA}/resources/emulatorlauncher/emulatorlauncher.sh" -system xbox360 -emulator xenia -core xenia -rom config

exit 0
