#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"; then
    export DISPLAY=$(getLocalXDisplay)
fi

exec "${USERDATA}/resources/emulatorlauncher/emulatorlauncher.sh" -system ps2 -emulator pcsx2 -rom config
