#!/bin/bash

if [ -n "$WAYLAND_DISPLAY" ]; then
    export SDL_VIDEODRIVER=wayland
    export SDL_VIDEO_WAYLAND_WMCLASS="batocera-config-ppsspp"
else
     export DISPLAY=$(getLocalXDisplay)
fi

"${USERDATA}/resources/emulatorlauncher/emulatorlauncher.sh" -system psp -emulator ppsspp -rom config
