#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

XDG_CONFIG_HOME="${USERDATA}/emuconfigs" \
XDG_DATA_HOME="${USERDATA}/saves/3ds" \
XDG_CACHE_HOME="${HOME}/.cache" \
SDL_JOYSTICK_HIDAPI=0 \
/usr/local/bin/azahar
