#!/bin/bash

if [ -n "$WAYLAND_DISPLAY" ]; then
    export SDL_VIDEODRIVER=wayland
    export SDL_VIDEO_WAYLAND_WMCLASS="batocera-config-ppsspp"
else
     export DISPLAY=$(getLocalXDisplay)
fi

XDG_CONFIG_HOME="${USERDATA}/emuconfigs" XDG_DATA_HOME="${USERDATA}/saves /usr/local/bin/ppsspp --windowed
