groups:
  GENERAL:
    submenus:
      GAME RENDERING & SHADERS:
        - name: SHADER SET
          value: shaderset
          description: ""
          preset: shaderset
        - name: SMOOTH GAMES (BILINEAR FILTERING)
          value: smooth
          description: Disabled if using a shader set or the output display matches the game's resolution.
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
        - name: INTEGER SCALING (PIXEL PERFECT)
          value: integerscale
          description: Only increase the image size in integer multiples.
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
      DECORATIONS:
        - name: DECORATION SET
          value: bezel
          description: ""
          preset: bezel
        - name: "STRETCH BEZELS (4K & ULTRAWIDE)"
          value: bezel_stretch
          description: ""
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
      AI GAME TRANSLATION:
        - name: ENABLE AI TRANSLATION SERVICE
          value: ai_service_enabled
          description: "During gameplay, press Hotkey + R1 to translate on-screen text. Only on libretro cores."
          preset: switchauto
        - name: TARGET LANGUAGE
          value: ai_target_lang
          description: The language to translate into.
          choices:
            - name: ENGLISH
              value: En
            - name: FRANÇAIS
              value: Fr
            - name: PORTUGUÊS
              value: Pt
            - name: DEUTSCH
              value: De
            - name: GREEK
              value: El
            - name: ESPAÑOL
              value: Es
            - name: CZECH
              value: Cs
            - name: DANISH
              value: Da
            - name: CROATIAN
              value: Hr
            - name: HUNGARIAN
              value: Hu
            - name: ITALIANO
              value: It
            - name: JAPANESE
              value: Ja
            - name: KOREAN
              value: Ko
            - name: DUTCH
              value: Nl
            - name: NORWEGIAN
              value: Nn
            - name: POLISH
              value: Po
            - name: ROMANIAN
              value: Ro
            - name: РУССКИЙ
              value: Ru
            - name: SVENSKA
              value: Sv
            - name: TÜRKÇE
              value: Tr
            - name: 简体中文
              value: Zh
        - name: AI TRANSLATION SERVICE URL
          value: ai_service_url
          description: "If nothing is specified, will use ZTranslate by default."
          preset: input
        - name: PAUSE ON TRANSLATED SCREEN
          value: ai_service_pause
          description: ""
          preset: switchauto
      LATENCY REDUCTION:
        - name: "RUN-AHEAD FRAMES"
          value: runahead
          description: "Enables run-ahead. Doubles CPU requirements. High numbers can result in visible jitter."
          choices:
            - name: None
              value: 0
            - name: 1
              value: 1
            - name: 2
              value: 2
            - name: 3
              value: 3
            - name: 4
              value: 4
            - name: 5
              value: 5
            - name: 6
              value: 6
        - name: "USE SECOND INSTANCE FOR RUN-AHEAD"
          value: secondinstance
          description: "Can prevent audio skips on button presses when using run-ahead."
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
        - name: "USE PRE-EMPTIVE FRAMES"
          value: preemptiveframes
          description: "Use preemptive frames instead of run-ahead. Only runs ahead when controller state changes."
          choices:
            - name: On
              value: true
            - name: Off
              value: false
        - name: AUTOMATIC FRAME DELAY
          value: video_frame_delay_auto
          description: Automatically decrease frame delay temporarily to prevent frame drops. Can introduce stuttering.
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
        - name: VARIABLE REFRESH RATE
          value: vrr_runloop_enable
          description: "Don't deviate from core requested timing. G-Sync, FreeSync, HDMI 2.1 VRR."
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
        - name: THREADED VIDEO
          value: video_threaded
          description: Improves performance at the cost of latency and more video stuttering.
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
        - name: VSYNC
          value: use_vsync
          description: Can cause conflict with KDE Plasma's Wayland compositor, but mitigates tearing on X11.
          preset: switchauto
    items:
      - name: DISCORD RPC
        value: discordrpc
        description: Enable Discord Rich Presence on emulators that support it.
        choices:
          - name: On
            value: 1
          - name: Off
            value: 0
      - name: GAME ASPECT RATIO
        value: ratio
        description: Force the game to render in this aspect ratio. Not all systems support all ratios.
        choices:
          - name: 4/3
            value: 4/3
          - name: 16/9
            value: 16/9
          - name: Full
            value: full
          - name: 16/10
            value: 16/10
          - name: 16/15
            value: 16/15
          - name: 21/9
            value: 21/9
          - name: 1/1
            value: 1/1
          - name: 2/1
            value: 2/1
          - name: 3/2
            value: 3/2
          - name: 3/4
            value: 3/4
          - name: 4/1
            value: 4/1
          - name: 9/16
            value: 9/16
          - name: 5/4
            value: 5/4
          - name: 6/5
            value: 6/5
          - name: 7/9
            value: 7/9
          - name: 8/3
            value: 8/3
          - name: 8/7
            value: 8/7
          - name: 19/12
            value: 19/12
          - name: 19/14
            value: 19/14
          - name: 30/17
            value: 30/17
          - name: 32/9
            value: 32/9
          - name: Config
            value: config
          - name: Square pixel
            value: squarepixel
          - name: Core provided
            value: core
          - name: Custom
            value: custom
      - name: REWIND
        value: rewind
        description: "Store past states to rewind to in realtime, if the core supports it."
        choices:
          - name: On
            value: 1
          - name: Off
            value: 0
      - name: AUTO SAVE/LOAD ON GAME LAUNCH
        value: autosave
        description: Load latest save state on game launch and save state when exiting game.
        choices:
          - name: On
            value: 1
          - name: Off
            value: 0
      - name: RUMBLE LEVEL
        value: rumble_gain
        description: For emulators and controllers supporting force feedback.
        choices:
          - name: disabled
            value: 1
          - name: "20%"
            value: 20
          - name: "40%"
            value: 40
          - name: "60%"
            value: 60
          - name: "80%"
            value: 80
          - name: "100%"
            value: 100
      - name: AUDIO VOLUME GAIN
        value: audio_volume
        description: Set game audio level gain in dB.
        choices:
          - name: "-12"
            value: "-12.0"
          - name: "-10"
            value: "-10.0"
          - name: "-8"
            value: "-8.0"
          - name: "-6"
            value: "-6.0"
          - name: "-4"
            value: "-4.0"
          - name: "-2"
            value: "-2.0"
          - name: 0 (No gain)
            value: 0
          - name: +2
            value: 2.0
          - name: +4
            value: 4.0
          - name: +6
            value: 6.0
          - name: +8
            value: 8.0
          - name: +10
            value: 10.0
          - name: +12
            value: 12.0
  CONTROLS:
    submenus:
      LIGHT GUNS:
        - name: USE LIGHT GUNS
          order: 99
          value: use_guns
          description: Use light guns instead of pads if light guns are connected.
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
      WHEELS:
        - name: USE WHEELS
          order: 100
          value: use_wheels
          description: Use wheels instead of pads if wheels are connected.
          choices:
            - name: On
              value: 1
            - name: Off
              value: 0
        - name: WHEEL ROTATION
          order: 100
          value: wheel_rotation
          description: Maximum wheel rotation from left to right (in degrees)
          choices:
            - name: 150
              value: 150
            - name: 180
              value: 180
            - name: 200
              value: 200
            - name: 240
              value: 240
            - name: 270
              value: 270
            - name: 360
              value: 360
            - name: 720
              value: 720
            - name: 900
              value: 900
            - name: 1080
              value: 1080
        - name: WHEEL DEADZONE
          order: 100
          value: wheel_deadzone
          description: Zone for which the game doesn't react to the wheel (in degrees)
          choices:
            - name: 5
              value: 5
            - name: 10
              value: 10
            - name: 15
              value: 15
            - name: 20
              value: 20
            - name: 25
              value: 25
            - name: 30
              value: 30
            - name: 35
              value: 35
            - name: 40
              value: 40
            - name: 45
              value: 45
            - name: 50
              value: 50
        - name: WHEEL MIDZONE
          order: 100
          value: wheel_midzone
          description: Reserve a non dead zone at the center of the wheel to go straight ahead (in degrees)
          choices:
            - name: 1
              value: 1
            - name: 2
              value: 2
            - name: 3
              value: 3
            - name: 4
              value: 4
            - name: 5
              value: 5
            - name: 6
              value: 6
            - name: 7
              value: 7
            - name: 8
              value: 8
            - name: 9
              value: 9
            - name: 10
              value: 10
  LIGHT GUN:
    items:
      - name: BORDER MODE
        value: bordersmode
        description: Show/Hide guns borders for specific systems
        choices:
          - name: normal
            value: normal
          - name: hidden
            value: hidden


sharedFeatures:
  - use_vsync
  - display_fps
  - discordrpc
  - powermode
  - batterymode
  - tdp
  - videomode
  - ratio
  - shaderset
  - smooth
  - integerscale
  - bezel
  - bezel_stretch
  - ai_service_enabled
  - ai_target_lang
  - ai_service_url
  - ai_service_pause
  - rewind
  - runahead
  - preemptiveframes
  - secondinstance
  - video_frame_delay_auto
  - vrr_runloop_enable
  - video_threaded
  - rumble_gain
emulator_name: _global_config
